### ISSUE TITLE
[Feature] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/gdsc-client#1]
## ✨ 어떤 작업인가요?
프로젝트 초기 세팅을 진행합니다.

## ☑ TODO
- [x] react, vite, ts 프로젝트 생성
- [x] 절대 경로 설정 및 절대 경로 자동 변환 설정
- [x] yarn berry 세팅
- [x] react-query 세팅
- [x] zustand 설치
- [x] emotion 세팅
- [x] eslint 규칙 추가
- [x] husky, lint-staged 세팅
- [x] cypress 세팅
- [x] vitest 세팅
- [x] 스토리북 세팅
- [x] chromatic에 스토리북 배포
